project:
  artifactId: api
  name: bbs
  description: microbbs
banner:
  location: banner.txt
server:
    port: 7000
    contextPath: /bbs
spring:
  http:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB
  datasource:
    driverClassName:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1/microbbs?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  session:
    store-type: redis
    cookie:
      http-only: true
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    show_sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl_auto: update
  #mvc:
    #static-path-pattern: /static/**
  resources:
    chain:
      html-application-cache: true
      enabled: true
      cache: true
      gzipped: true
      strategy:
        content:
          enabled: true
          paths: /**

security:
  headers:
    cache: true
    xss: true
    enable-csrf: false
  ignored: /static/**
  user:
    password: 111111
  basic:
    enabled:  true
  require_ssl: false

oauth2:
  weibo:
    clientId: 2469375966
    clientSecret: 0f0b097b256ed88bb9f21037e36604b8
  lms:
     clientId: 1xx1255436
     clientSecret: 7x0b09ssb256ed88bb9f21037e36604b7

site:
  server: http://meiqiu.ngrok.cc/bbs

logging:
  level:
    ROOT: WARN
    org.apache.http: WARN
    # turn up to DEBUG to diagnose GitHub API issues
    org.apache.http.headers: WARN
    # turn up to DEBUG to see information about guides as they are fetched and processed
    sagan.guides.support: WARN
    # always log high-level information about application startup
    sagan.SiteApplication: INFO
    # log generated password for admin endpoints, e.g. /env, /beans
    # See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: INFO
